/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured external sources */
        get: operations["listSources"];
        put?: never;
        /** Create an external source */
        post: operations["createSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable source identifier. */
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        /** Get a configured external source */
        get: operations["getSource"];
        /** Replace an external source configuration */
        put: operations["updateSource"];
        post?: never;
        /** Delete an external source */
        delete: operations["deleteSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/collection-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent completed collection runs */
        get: operations["listCollectionRuns"];
        put?: never;
        /** Start a manual collection run */
        post: operations["startCollectionRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/collection-runs/{collectionRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionRunId: string;
            };
            cookie?: never;
        };
        /** Get one completed collection run */
        get: operations["getCollectionRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/analysis/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent normalized analysis items */
        get: operations["listAnalysisItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/analysis/items/{normalizedItemId}": {
        parameters: {
            query: {
                monitoringProfileId: string;
            };
            header?: never;
            path: {
                normalizedItemId: string;
            };
            cookie?: never;
        };
        /** Get one profile-scoped normalized analysis item */
        get: operations["getAnalysisItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SourceType: "REST" | "RSS" | "HTML";
        Source: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["SourceType"];
            /**
             * Format: uri
             * @description Absolute HTTP(S) source URL without embedded credentials or a fragment.
             */
            location: string;
            enabled: boolean;
            /** @description Source-type-specific string configuration interpreted by the owning collector. */
            settings: {
                [key: string]: string;
            };
        };
        SourceUpsertRequest: {
            name: string;
            type: components["schemas"]["SourceType"];
            /**
             * Format: uri
             * @description Absolute HTTP(S) source URL without embedded credentials or a fragment.
             */
            location: string;
            enabled: boolean;
            /**
             * @description Source-type-specific string configuration interpreted by the owning collector.
             * @default {}
             */
            settings: {
                [key: string]: string;
            };
        };
        CollectionRunRequest: {
            monitoringProfileId: string;
            informationCategory: string;
        };
        CollectionSourceRun: {
            /** Format: uuid */
            sourceId: string;
            /** @enum {string} */
            status: "PUBLISHED" | "FETCH_FAILED" | "PUBLICATION_FAILED";
            rawItemId: string | null;
            eventId: string | null;
            failureMessage: string | null;
        };
        CollectionRun: {
            /** Format: uuid */
            collectionRunId: string;
            monitoringProfileId: string;
            informationCategory: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string;
            /** @enum {string} */
            status: "SUCCEEDED" | "PARTIALLY_SUCCEEDED" | "FAILED";
            /** Format: int64 */
            publishedCount: number;
            /** Format: int64 */
            failedCount: number;
            sources: components["schemas"]["CollectionSourceRun"][];
        };
        AnalysisItemInspection: {
            monitoringProfileId: string;
            normalizedItemId: string;
            sourceId: string;
            externalId: string | null;
            /** Format: uri */
            sourceUrl: string;
            firstRawItemId: string;
            firstSourceEventId: string;
            /** Format: date-time */
            firstSeenAt: string;
            lastRawItemId: string;
            lastSourceEventId: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: int64 */
            discoveryCount: number;
        };
    };
    responses: never;
    parameters: {
        /** @description Stable source identifier. */
        SourceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
        };
    };
    createSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpsertRequest"];
            };
        };
        responses: {
            /** @description Source created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Invalid source configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable source identifier. */
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable source identifier. */
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpsertRequest"];
            };
        };
        responses: {
            /** @description Source updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Invalid source configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable source identifier. */
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCollectionRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent collection runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionRun"][];
                };
            };
        };
    };
    startCollectionRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionRunRequest"];
            };
        };
        responses: {
            /** @description Completed collection run */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionRun"];
                };
            };
            /** @description Invalid run request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCollectionRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionRunId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionRun"];
                };
            };
            /** @description Collection run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAnalysisItems: {
        parameters: {
            query?: {
                limit?: number;
                monitoringProfileId?: string;
                sourceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis item inspection state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisItemInspection"][];
                };
            };
        };
    };
    getAnalysisItem: {
        parameters: {
            query: {
                monitoringProfileId: string;
            };
            header?: never;
            path: {
                normalizedItemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis item inspection state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisItemInspection"];
                };
            };
            /** @description Analysis item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
